name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    uses: CloudyWing/devops-templates/.github/workflows/reusable-nuget-publish.yml@main
    with:
      dotnet-version: '10.0.x'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
